page_gen-dirs: true

page_gen:
  - data: roms.nes
    name: key
    template: romdetail
    dir: roms/nes
  - data: roms.snes
    name: key
    template: romdetail
    dir: roms/snes
  - data: roms.gba
    name: key
    template: romdetail
    dir: roms/gba
  - data: roms.nes
    name: key
    template: playrom
    dir: play/nes
  - data: tags
    name: tag
    template: roms-by-tag
    dir: roms/nes/by-tag