page_gen-dirs: true

page_gen:
  - data: roms_index
    name: key
    template: romdetail
    dir: roms
  - data: roms_index
    name: key
    template: playrom
    dir: play
  - data: tags
    name: tag
    template: roms-by-tag
    dir: roms/by-tag