page_gen-dirs: true

page_gen:
  - data: roms.nes
    name: key
    template: romdetail
    dir: roms/nes
  - data: roms.snes
    name: key
    template: romdetail
    dir: roms/snes
  - data: roms.gba
    name: key
    template: romdetail
    dir: roms/gba
  - data: roms.atari2600
    name: key
    template: romdetail
    dir: roms/atari2600
  - data: roms.colecovision
    name: key
    template: romdetail
    dir: roms/colecovision
  - data: roms.sms
    name: key
    template: romdetail
    dir: roms/sms
  - data: roms.nes
    name: key
    template: playrom
    dir: play/nes
  - data: tags
    name: tag
    template: roms-by-tag
    dir: roms/nes/by-tag